
package Vista;

import Modelo.ModeloTablaPedidos;
import Controlador.ListenerAñadirPedido;
import Modelo.LineaPedidoDB;
import Modelo.PedidoDB;
import Modelo.ProductoDB;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JTable;


public class Cantidad extends javax.swing.JDialog {

    public Cantidad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    
    
    public Cantidad(java.awt.Frame parent, boolean modal, final JTable tabla, final int id) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);//coloca ventana en el centro
        
        this.jButton1.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                if(tabla.getSelectedRow()!=-1){
                    String datos[]=new String [3];
                    datos[0]=(String) ((ModeloTablaPedidos)tabla.getModel()).getValueAt(tabla.getSelectedRow(), 0);
                    datos[1]=(String) ((ModeloTablaPedidos)tabla.getModel()).getValueAt(tabla.getSelectedRow(), 1);
                    datos[2]=(String) ((ModeloTablaPedidos)tabla.getModel()).getValueAt(tabla.getSelectedRow(), 2); 
                    int idProducto = ProductoDB.getId( datos[0], datos[1], datos[2]);
                    double precioUnidad=LineaPedidoDB.getPrecioUnidad(id, idProducto);
                    int nuevaCant=Integer.parseInt(jTextField1.getText());
                    double nuevoPrecio=nuevaCant*precioUnidad;
                    LineaPedidoDB.setCantidad(nuevaCant, nuevoPrecio,id, idProducto);
                    double precioTotal=0;
                    ModeloTablaPedidos modeloPedido=new ModeloTablaPedidos(LineaPedidoDB.getLineasPedido(id));
                    tabla.setModel(modeloPedido);
                    for(int cont=0;cont<((ModeloTablaPedidos)tabla.getModel()).getRowCount();cont++){
                        precioTotal+=(double)((ModeloTablaPedidos)tabla.getModel()).getValueAt(cont, 4);
                    }
                    PedidoDB.setPrecio(id,precioTotal);
                }
                dispose();
            }
        });
    }

    public Cantidad(java.awt.Frame parent, boolean modal, final ListenerAñadirPedido aThis) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);//coloca ventana en el centro
        
        this.jButton1.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                aThis.devolverElemento(jTextField1);
                dispose();
            }
        });
    }
    
    public Cantidad(java.awt.Frame parent, boolean modal, final ListenerAñadirPedido aThis, int id) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);//coloca ventana en el centro
        
        this.jButton1.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                aThis.devolverElementoModificacion(jTextField1);
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CANTIDAD:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("ok");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cantidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cantidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cantidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cantidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cantidad dialog = new Cantidad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
